Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2023
Var
// Seção de Declarações das variáveis 
   count: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto (count < 10) faca
       count <- count + 1
       escreval(count)
       
   fimenquanto

Fimalgoritmo